book_recommendation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user.views import home
from notifications.views import get_notifications, get_notifications_click
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path("user/", include("user.urls")),
    path("movies/", include("movies.urls")),
    path("", home, name="home"),
    path("notifications", get_notifications, name="notifications"),
    path("notifications_click", get_notifications_click, name="notifications_click")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_recommendation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user.views import home
from notifications.views import get_notifications, get_notifications_click
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path("user/", include("user.urls")),
    path("movies/", include("movies.urls")),
    path("", home, name="home"),
    path("notifications", get_notifications, name="notifications"),
    path("notifications_click", get_notifications_click, name="notifications_click")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import MyItems, RecentlyAdded, search, MovieDeleteView, MovieDetailView, MovieUpdateView, recommend_movies

urlpatterns = [
    path("myitems/", MyItems, name="my_movies"),
    path("recently_added", RecentlyAdded, name="recently_added"),
    path('detail/<int:pk>/', MovieDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/update/', MovieUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/delete/', MovieDeleteView.as_view(), name='delete'),
    path('search/', search, name='search'),
    path('recommend/', recommend_movies, name="recommend")
]

user/urls.py
from django.urls import path
from .views import get_started, ProfileView, LoginView, SignupView, LogoutView
urlpatterns=[
    path("get_started/", get_started, name="get_started"),
    path("profile/", ProfileView, name="profile"),
    path("signup/", SignupView, name="signup"),
    path("login/", LoginView, name="signin"),
    path("logout/", LogoutView, name="logout")
]

movies/models.py
from django.db import models
from user.models import Category
from django.contrib.auth.models import User


# Create your models here.


class Movies(models.Model):
    name = models.CharField(max_length=100)
    cast = models.TextField()
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    url = models.URLField(max_length=300)
    info_user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie_image = models.ImageField(upload_to='movie_pic', default="movie_pic/default.png")


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django.forms import ModelForm, TextInput
from django import forms
from .models import Movies


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = ['name', 'url', 'cast', 'description', 'category', 'movie_image']
        exclude = ['info_user']
        widgets = {
            'cast': forms.TextInput(attrs={'class': 'form_cast', 'rows': 4, 'cols': 4}),
            'description': forms.TextInput(attrs={'class': 'form_description', 'rows': 4, 'cols': 4}),

        }

movies/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from user.models import Category
from .forms import MovieForm
from .models import Movies, History
from notifications.models import Notification
from movie_recommendation.settings import MEDIA_URL
import nltk
import re
import numpy as np
import contractions
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

nltk.download('punkt')


# Create your views here.
def MyItems(request):
    if request.method == 'POST':
        print(request.POST)
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            print('form is valid')
            add_user = form.save(commit=False)
            add_user.info_user = request.user
            add_user.save()
            Notification.objects.create(message=f'{request.user} have added a new movie {request.POST["name"]}',
                                        user=request.user)
            return redirect("recently_added")

    elif request.method == 'GET':
        form = MovieForm()
    context = {
        'form': form,
        'menuindex': 4

    }
    return render(request, 'movies/my_items.html', context)


class MovieDetailView(DetailView):
    model = Movies
    template_name = "movies/movies_detail.html"

    def get_context_data(self, **kwargs):
        History.objects.create(user=self.request.user, movie=Movies.objects.get(id=self.kwargs['pk']))
        context = super(MovieDetailView, self).get_context_data(**kwargs)
        context['MEDIA_URL'] = MEDIA_URL
        return context


class MovieUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Movies
    fields = ['name', 'cast', 'description', 'category', 'movie_image']
    success_url = '/'
    template_name = "movies/movies_form.html"

    def form_valid(self, form):
        form.instance.info_user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        desc = self.get_object()
        if self.request.user == desc.info_user:
            return True
        return False


class MovieDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Movies
    success_url = '/'
    template_name = "movies/movies_confirm_delete.html"

    def test_func(self):
        desc = self.get_object()
        if self.request.user == desc.info_user:
            return True
        return False


def search(request):
    query = request.GET['query']
    if len(query) > 85:
        movie = []
    else:
        Mname = Movies.objects.filter(name__icontains=query)
        Mdesc = Movies.objects.filter(description__icontains=query)
        movie = Mname.union(Mdesc)
        paginator = Paginator(list(movie), 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
    params = {'page_obj': page_obj, 'query': query}
    return render(request, 'movies/search.html', params)


def movie_history(request):
    history = History.objects.filter(user_id=request.user.id).order_by("created_at")[::-1][:5]
    print("history", history)
    movie_name_list = []
    for h in history:
        movie_name = h.movie.name
        movie_name_list.append(movie_name)
    movie_name_set = set(movie_name_list)  # to retrieve only the unique movie name
    return movie_name_set


def normalize_document(doc):
    # lower case and remove special characters\whitespaces
    doc = re.sub(r'[^a-zA-Z0-9\s]', '', doc, re.I | re.A)
    doc = doc.lower()
    doc = doc.strip()
    doc = contractions.fix(doc)
    # tokenize document
    tokens = nltk.word_tokenize(doc)
    stop_words = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll",
                  "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's",
                  'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs',
                  'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is',
                  'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did',
                  'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at',
                  'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after',
                  'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again',
                  'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both',
                  'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same',
                  'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've",
                  'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn',
                  "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't",
                  'ma', 'mightn', "mightn't", 'must', 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't",
                  'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc


def get_movie_list():
    tfidf = TfidfVectorizer(ngram_range=(1, 2), min_df=2)

    # creating dataframe for recommendation engine
    movies_object = list(Movies.objects.values())
    movies_df = pd.DataFrame(movies_object)

    category_object = list(Category.objects.values())
    category_df = pd.DataFrame(category_object)

    category_df.columns = ['category_id', 'category_name']
    main_data = movies_df.merge(category_df, how="left", on="category_id")

    # preprocessing
    normalized_corpus = np.vectorize(normalize_document)
    norm_corpus = normalized_corpus(list(main_data['description']))

    df = pd.DataFrame({'description': norm_corpus,
                       'category': np.array(main_data['category_name'])})

    # vectorization
    tfidf_matrix = tfidf.fit_transform(df['description'] + df['category'])
    print(tfidf_matrix.shape)

    # similarity_scores
    doc_sim = cosine_similarity(tfidf_matrix)
    doc_sim_df = pd.DataFrame(doc_sim)

    # finding given movie id
    movie_list = main_data['name'].values

    return doc_sim_df, movie_list


def recommender_engine(movie_title, movie_list, doc_sim_df):
    movie_idx = np.where(movie_list == str(movie_title))[0][0]
    movie_similarities = doc_sim_df.iloc[movie_idx].values
    similar_movie_idxs = np.argsort(-movie_similarities)[1:3]
    similar_movie = movie_list[similar_movie_idxs]

    return similar_movie


def RecentlyAdded(request):
    u = User.objects.all()
    desc = Movies.objects.all()
    paginator = Paginator(desc, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'movies/recently_added.html',
                  {'desc': desc, 'u': u, 'MEDIA_URL': MEDIA_URL, "menuindex": 3, "heading": "Recently Added Movies",
                   "page_obj": page_obj})


def get_recommended_movies(movie_name_set):
    doc_sim_df, movie_list = get_movie_list()
    similar_movies = []
    for i in movie_name_set:
        similar_movie = recommender_engine(i, movie_list=movie_list, doc_sim_df=doc_sim_df)
        similar_movies.append(similar_movie)
    movieList = [item for elem in similar_movies for item in elem]
    sb = set(movieList)
    return sb


def recommend_movies(request):
    movie_name_set = movie_history(request)
    try:
        sb = get_recommended_movies(movie_name_set)
    except:
        print("Error")
        sb = []

    l = []
    for i in sb:
        l.append(Movies.objects.filter(name=i).last())
    print("L:", l)
    paginator = Paginator(l, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    print("ppppppppppppppppppp", page_obj)
    return render(request, 'movies/recommended_movies.html',
                  {'MEDIA_URL': MEDIA_URL, "menuindex": 6, "page_obj": page_obj, "heading": "Recommended Movies"})

movies/templates/movies/home.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <div>
        <div style="float: left; width: 50%; border: 1px solid black; height: 100%;">
            <p style="margin-top: 25%;">With the Movie Recommender app, you can view personalized recommendations based
                on your favorite categories chosen and history.</p>

        </div>
        <div style="float: right; width: 50%; border: 1px solid black; height: 100%;">
            <img style="width: 100%; height: 100%" src="{% static 'images/movies_recommender.jpeg' %}"/>
        </div>
    </div>
{% endblock %}

movies/templates/movies/movies_confirm_delete.html
{% extends 'base.html' %}
{% block body %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <fieldset>
            <legend>
                Delete
            </legend>
            <h2>Are you sure to delete {{ object.name }}</h2>
        </fieldset>
        <button class="btn btn-outline-danger" type="submit">Yes</button>
        <a href="{% url 'detail' object.id %}" class="btn btn-outline-secondary">Cancel</a>
    </form>
{% endblock %}

movies/templates/movies/movies_form.html
{% extends 'base.html' %}
{% load static %}
{% block pagecss %}
    {% load crispy_forms_tags %}
    {#		<link rel="stylesheet" href="{% static 'css/theme-elements.css' %}">#}
    <style>


        /* Featured Box */
        .featured-box {
            background: #FFF;
            box-sizing: border-box;
            border-bottom: 1px solid #DFDFDF;
            border-left: 1px solid #ECECEC;
            border-radius: 8px;
            border-right: 1px solid #ECECEC;
            box-shadow: 0 2px 4px 0px rgba(0, 0, 0, 0.05);
            margin-bottom: 20px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            min-height: 100px;
            position: relative;
            text-align: center;
            z-index: 1;
        }

        .featured-box h4 {
            font-size: 1.3em;
            font-weight: 400;
            letter-spacing: -0.7px;
            margin-top: 5px;
            margin-bottom: 5px;
        }

        .featured-box .box-content {
            border-radius: 8px;
            border-top: 1px solid rgba(0, 0, 0, 0.06);
            border-top-width: 4px;
            padding: 28.8px;
            padding: 1.8rem;
            position: relative;
        }

        .featured-box .box-content:not(.box-content-border-0) {
            top: -1px;
            border-top-width: 4px;
        }

        .featured-box .box-content.box-content-border-0 {
            border-top: 1px solid rgba(0, 0, 0, 0.06) !important;
            border-bottom: 0 !important;
        }

        .featured-box .box-content.box-content-border-bottom {
            top: 1px;
        }

        .featured-box .box-content-border-bottom {
            border-top: 1px solid rgba(0, 0, 0, 0.06) !important;
            border-bottom: 4px solid rgba(0, 0, 0, 0.06);
        }

        textarea {
            width: 100px;
            height: 30px;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="row justify-content-center">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                {% if message.tags == "success" %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="col-6">
            <div class="featured-box featured-box-primary text-start mt-0">
                <div class="box-content">
                    <h4 class="color-primary font-weight-semibold text-4 text-uppercase mb-3 text-center">Update</h4>
                    <form method="post" enctype="multipart/form-data" class="sell-form">
                        {% csrf_token %}

                        {{ form|crispy }}
                        <br>
                        <br>
                        <button type="submit">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

movies/templates/movies/my_items.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block pagecss %}

    <style>


        /* Featured Box */
        .featured-box {
            background: #FFF;
            box-sizing: border-box;
            border-bottom: 1px solid #DFDFDF;
            border-left: 1px solid #ECECEC;
            border-radius: 8px;
            border-right: 1px solid #ECECEC;
            box-shadow: 0 2px 4px 0px rgba(0, 0, 0, 0.05);
            margin-bottom: 20px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            min-height: 100px;
            position: relative;
            text-align: center;
        }

        .featured-box h4 {
            font-size: 1.3em;
            font-weight: 400;
            letter-spacing: -0.7px;
            margin-top: 5px;
            margin-bottom: 5px;
        }

        .featured-box .box-content {
            border-radius: 8px;
            border-top: 1px solid rgba(0, 0, 0, 0.06);
            border-top-width: 4px;
            padding: 28.8px;
            padding: 1.8rem;
            position: relative;
        }

        .featured-box .box-content:not(.box-content-border-0) {
            top: -1px;
            border-top-width: 4px;
        }

        .featured-box .box-content.box-content-border-0 {
            border-top: 1px solid rgba(0, 0, 0, 0.06) !important;
            border-bottom: 0 !important;
        }

        .featured-box .box-content.box-content-border-bottom {
            top: 1px;
        }

        .featured-box .box-content-border-bottom {
            border-top: 1px solid rgba(0, 0, 0, 0.06) !important;
            border-bottom: 4px solid rgba(0, 0, 0, 0.06);
        }

        #id_name, #id_url, #id_cast, #id_description, #id_category {
            width: 500px;
        }

        @media only screen and (max-width: 1000px) {

            .featured-box {
                background: #FFF;
                border-bottom: none;
                border-left: none;
                border-radius: 0px;
                border-right: none;
                box-shadow: none;
                margin-bottom: 20px;
                margin-left: auto;
                margin-right: auto;
                margin-top: 20px;

            }

            .featured-box .box-content {
                border-radius: 8px;
                border-top: 1px solid rgba(0, 0, 0, 0.06);
                border-top-width: 4px;
                position: absolute;
                width: 500px;

            }

            .featured-box .box-content:not(.box-content-border-0) {
                top: -1px;
                border-top-width: 4px;
                left: -300px;
            }

            .featured-box .box-content.box-content-border-0 {
                border-top: 1px solid rgba(0, 0, 0, 0.06) !important;
                border-bottom: 0 !important;
            }

            .featured-box .box-content.box-content-border-bottom {
                top: 1px;
            }

            .featured-box .box-content-border-bottom {
                border-top: 1px solid rgba(0, 0, 0, 0.06) !important;
                border-bottom: 4px solid rgba(0, 0, 0, 0.06);
            }

            #id_name, #id_url, #id_cast, #id_description, #id_category {
                width: 200px;
            }

        }
    </style>
{% endblock %}
{% block body %}
    <div class="row justify-content-center" style="width: 1200px; margin-top: 20px; margin-left: 10%;">

        <div class="col-6">
            <div class="featured-box featured-box-primary text-start mt-0">
                <div class="box-content">
                    <h3>Movie Form</h3>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {{ form|crispy }}
                        <br>
                        <button type="submit" class="btn btn-primary"
                                style="background-color: #333; border-color: #333;">Submit
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

movies/templates/movies/recently_added.html
{% extends 'base.html' %}
{% block body %}
    {% include "movies/recently_added_base.html" %}
{% endblock %}

movies/templates/movies/recently_added_base.html
{% load static %}
<!-- Vendor CSS -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">

<!-- Theme CSS -->
{#<link rel="stylesheet" href="{% static 'css/theme.css' %}">#}
{#<link rel="stylesheet" href="{% static 'css/custom.css' %}">#}
{#<link rel="stylesheet" href="{% static 'css/theme-elements.css' %}">#}
{#<link rel="stylesheet" href="{% static 'css/theme-shop.css' %}">#}
{#<link rel="stylesheet" href="{% static 'css/theme-blog.css' %}">#}

<style>
    .change-color{
        background-color: #333 !important;
        border-color: #333 !important;
    }
   .navbar-brand{
       font-size: 20px;
   }
</style>


<!--Search -->
<div style="float: right; margin: 20px;">
    <form method="get" action="{% url 'search' %}" class="form-inline ">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query"
               id="query" style="width: 400px;">
        <button class="btn btn-primary change-color" type="submit" id="search_button">Search</button>
    </form>
</div>
<!-- End Search-->

<div class="row" style="margin-top: 5%;
        margin-left: 5%;
width: 100%;">
    <div class="col">
        <div class="blog-posts">
            <div class="row" style="margin-top: 5%;
        margin-left: 5%;
padding-bottom: 100px;">

                {% for moviesdetail in page_obj %}
                    <div class="col-md-4" style="width: 400px; padding-left: 50px;">
                        <article class="post post-medium border-0 pb-0 mb-5">
                            <div class="post-image">
                                <a href="{% url 'detail' moviesdetail.id %}">

                                    <img src="{{ MEDIA_URL }}{{ moviesdetail.movie_image }}"
                                         class="img-fluid img-thumbnail img-thumbnail-no-borders rounded-0" alt="abc"/>
                                </a>
                            </div>

                            <div class="post-content">


                                <div class="post-meta">
                                    <img class="card__thumb" src="{{ moviesdetail.info_user.profile.image.url }}" alt=""
                                         style="width: 20px; height: 20px;"/>
                                    <span class="card__status">Posted By: {{ moviesdetail.info_user.username }}</span>
                                    <div class="card__header-text">
                                        <h3 class="card__title">{{ moviesdetail.name }}</h3>
                                        <p>{{ moviesdetail.url }}</p>
                                        <span class="card__status">{{ moviesdetail.category }}</span>
                                    </div>
                                </div>

                            </div>
                        </article>
                    </div>
                {% endfor %}


            </div>

        </div>
    </div>
</div>

<div class="pagination" style="float: right; position: relative; bottom: 10%;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary change-color" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary change-color" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}


        {% if page_obj.has_next %}
            <a class="btn btn-primary change-color" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-primary change-color" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

movies/templates/movies/recommended_movies.html
{% extends 'base.html' %}
{% block body %}
    {% include "movies/recently_added_base.html" %}
{% endblock %}

movies/templates/movies/search.html
{% extends 'base.html' %}
{% block pagecss %}
    <link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">

    <link rel="stylesheet" href="css/theme.css">
    <link rel="stylesheet" href="css/custom.css">
    <link rel="stylesheet" href="css/theme-elements.css">
    <link rel="stylesheet" href="css/theme-shop.css">
    <link rel="stylesheet" href="css/theme-blog.css">

    <link rel="stylesheet" href="css/default.css">

    <link rel="stylesheet" href="css/custom.css">
{% endblock %}

{% block body %}
    <div style="float: right; margin: 20px;">
        <form method="get" action="{% url 'search' %}" class="form-inline ">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query"
                   id="query" style="width: 400px;">
            <button class="btn btn-primary" type="submit" id="search_button">Search</button>
        </form>
    </div>

    <div class="row" style="margin-top: 5%;
        margin-left: 10%;">
        <div class="col">
            <div class="blog-posts">
                <div class="row" style="margin-top: 5%;
        margin-left: 10%;">

                    {% for moviesdetail in page_obj %}
                        <div class="col-md-4">
                            <article class="post post-medium border-0 pb-0 mb-5">
                                <div class="post-image">
                                    <a href="{% url 'detail' moviesdetail.id %}">

                                        <img src="/movies/media/{{ moviesdetail.movie_image }}"
                                             class="img-fluid img-thumbnail img-thumbnail-no-borders rounded-0"
                                             alt="abc"/>
                                    </a>
                                </div>

                                <div class="post-content">


                                    <div class="post-meta">
                                        <!-- User Image -->
                                        <img class="card__thumb" src="{{ moviesdetail.info_user.profile.image.url }}"
                                             alt="" style="width: 20px; height: 20px;"/>
                                        <span class="card__status">Posted By: {{ moviesdetail.info_user.username }}</span>
                                        <div class="card__header-text">
                                            <h3 class="card__title">{{ moviesdetail.name }}</h3>
                                            <p>{{ moviesdetail.url }}</p>
                                            <span class="card__status">{{ moviesdetail.category }}</span>
                                        </div>
                                    </div>

                                </div>
                            </article>
                        </div>
                    {% endfor %}


                </div>

            </div>
        </div>
    </div>

    <div class="pagination" style="float: right; position: relative; bottom: 10%;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}


        {% if page_obj.has_next %}
            <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}